spring:
  application: name:user-center
  #DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.143.137.139:3306/wcw001
    username: wcw001
    password: wcw231407
  session:
    timeout: 86400
server:
  address: 0.0.0.0
